name: Roslyn Branches

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

defaults:
  run:
    working-directory: .\#scripts\roslyn-branches

jobs:
  generate-matrix:
    runs-on: windows-latest
    outputs:
      matrix: ${{steps.generate-matrix.outputs.matrix}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
      - name: npm ci
        run: |
          npm ci
      - id: generate-matrix
        name: generate run matrix
        run: |
          npm run generate-run-matrix

  build-branch:
    needs: generate-matrix
    runs-on: windows-latest
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
      fail-fast: false
    continue-on-error: ${{matrix.optional}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
      - uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.0.x
      - name: npm ci
        run: |
          npm ci
      - name: build branch
        env:
          SHARPLAB_TELEMETRY_KEY: ${{secrets.AzureBranchTelemetryKey}}
          SL_DEPLOY_MODE:         Azure
          SL_BUILD_AZURE_TENANT:  ${{secrets.AzureTenant}}
          SL_BUILD_AZURE_APP_ID:  ${{secrets.AzureAppID}}
          SL_BUILD_AZURE_SECRET:  ${{secrets.AzureSecret}}
        run: |
          npm run build-branch -- ${{matrix.branch}}